import type { Metadata } from "next";
import localFont from "next/font/local";
import { Noto_Kufi_Arabic } from "next/font/google";
import Header from '@/components/Header';
import "./globals.css";
import ClientProvider from "@/components/ClientProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const kufi = Noto_Kufi_Arabic({ subsets: ['arabic'], weight: ['100', '700', '900'] })

export const metadata: Metadata = {
  title: "Markify App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClientProvider>
        <body>
          <Header />
          <main>{children}</main>
        </body>
      </ClientProvider>
    </html>
  );
}
